# Generated by Django 4.2.2 on 2023-06-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_remove_perfil_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='sector',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
